### Creates a New User
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "first_name": "Dev",
  "last_name": "Ort",
  "email": "devort@example.com",
  "phone": "1234567890",
  "password": "password",
  "password_confirmation": "password"
}

### Creates a New Session
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "devort@example.com",
  "password": "password"
}

### Card Index
GET http://localhost:3000/cards.json
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDUyNDE4NjV9.jewynWzBD7Zhjn0GopyvoNGtASH6lo1p_Og0TioMmqw
Content-Type: application/json

### Card Show
GET http://localhost:3000/cards.json
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDUyNDE4NjV9.jewynWzBD7Zhjn0GopyvoNGtASH6lo1p_Og0TioMmqw
Content-Type: application/json

{
  "card_id": 1
}

### Create Card
POST http://localhost:3000/cards.json
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDUyNDE4NjV9.jewynWzBD7Zhjn0GopyvoNGtASH6lo1p_Og0TioMmqw
Content-Type: application/json

{
  "card": "This is my card test"
}

### Update Card
PATCH http://localhost:3000/cards.json
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDUyNDE4NjV9.jewynWzBD7Zhjn0GopyvoNGtASH6lo1p_Og0TioMmqw
Content-Type: application/json

{
  "card_id": 1,
  "card": "Card test"
}